"""Posts API — create drafts, then publish now or schedule via Zernio."""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user
from app.core.clients import client_scope
from app.core.user_keys import resolve_zernio_key
from app.db.session import get_db
from app.models import post as post_status
from app.models.account import LinkedInAccount
from app.models.post import Post
from app.models.user import User
from app.schemas.post import PostCreate, PostOut, PostUpdate, ScheduleRequest
from app.services import publisher

router = APIRouter(prefix="/posts", tags=["posts"])


async def _get_owned_post(post_id: int, user: User, db: AsyncSession) -> Post:
    post = await db.get(Post, post_id)
    if not post or post.user_id != user.id:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Post not found")
    return post


async def _get_owned_account(account_id: int, user: User, db: AsyncSession) -> LinkedInAccount:
    account = await db.get(LinkedInAccount, account_id)
    if not account or account.user_id != user.id:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Linked account not found")
    return account


@router.post("", response_model=PostOut, status_code=201)
async def create_post(
    body: PostCreate,
    current: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Post:
    account = await _get_owned_account(body.account_id, current, db)  # ownership check
    post = Post(
        user_id=current.id,
        account_id=body.account_id,
        platform=account.platform,
        body=body.body,
        hashtags=body.hashtags,
        media=body.media,
        first_comment=body.first_comment,
        infographic_html=body.infographic_html,
        status=post_status.DRAFT,
        client_id=current.active_client_id,
    )
    db.add(post)
    await db.commit()
    await db.refresh(post)
    return post


@router.get("", response_model=list[PostOut])
async def list_posts(
    current: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
    status_filter: str | None = Query(None, alias="status"),
    campaign_id: int | None = Query(None),
) -> list[Post]:
    stmt = (
        select(Post)
        .where(Post.user_id == current.id, client_scope(Post.client_id, current.active_client_id))
        .order_by(Post.created_at.desc())
    )
    if status_filter:
        stmt = stmt.where(Post.status == status_filter)
    if campaign_id is not None:
        stmt = stmt.where(Post.campaign_id == campaign_id)
    rows = await db.scalars(stmt)
    return list(rows)


@router.get("/{post_id}", response_model=PostOut)
async def get_post(
    post_id: int,
    current: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Post:
    return await _get_owned_post(post_id, current, db)


@router.get("/{post_id}/infographic")
async def get_post_infographic(
    post_id: int,
    current: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> dict[str, str | None]:
    """Return the post's infographic HTML (generated by an autopilot campaign)."""
    post = await _get_owned_post(post_id, current, db)
    if not post.infographic_html:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "No infographic for this post")
    return {"html": post.infographic_html}


@router.patch("/{post_id}", response_model=PostOut)
async def update_post(
    post_id: int,
    body: PostUpdate,
    current: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Post:
    post = await _get_owned_post(post_id, current, db)
    if post.status == post_status.PUBLISHED:
        raise HTTPException(status.HTTP_409_CONFLICT, "Cannot edit a published post")
    data = body.model_dump(exclude_unset=True)
    for field, value in data.items():
        setattr(post, field, value)
    await db.commit()
    await db.refresh(post)
    return post


@router.delete("/{post_id}", status_code=204, response_model=None)
async def delete_post(
    post_id: int,
    current: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> None:
    post = await _get_owned_post(post_id, current, db)
    # If it's still scheduled on Zernio, cancel it there FIRST — otherwise Zernio
    # owns the clock and would publish it even though we removed our copy.
    if post.status == post_status.SCHEDULED and post.zernio_post_id:
        zkey = resolve_zernio_key(current)
        try:
            await publisher.cancel(post, zkey)
        except publisher.PublishError as e:
            raise HTTPException(e.status_code, e.message) from e
    await db.delete(post)
    await db.commit()


@router.post("/{post_id}/publish", response_model=PostOut)
async def publish_post(
    post_id: int,
    current: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Post:
    post = await _get_owned_post(post_id, current, db)
    if post.status == post_status.PUBLISHED:
        raise HTTPException(status.HTTP_409_CONFLICT, "Post already published")
    account = await _get_owned_account(post.account_id, current, db)
    zkey = resolve_zernio_key(current)
    if not zkey:
        raise HTTPException(400, "Connect your channels first.")

    try:
        await publisher.publish_now(post, account.zernio_account_id,
                                    platform=account.platform, zernio_key=zkey)
    except publisher.PublishError as e:
        await db.commit()  # persist FAILED status/error set by the service
        raise HTTPException(e.status_code, e.message) from e

    await db.commit()
    await db.refresh(post)
    return post


@router.post("/{post_id}/schedule", response_model=PostOut)
async def schedule_post(
    post_id: int,
    body: ScheduleRequest,
    current: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Post:
    post = await _get_owned_post(post_id, current, db)
    if post.status == post_status.PUBLISHED:
        raise HTTPException(status.HTTP_409_CONFLICT, "Post already published")
    account = await _get_owned_account(post.account_id, current, db)
    zkey = resolve_zernio_key(current)
    if not zkey:
        raise HTTPException(400, "Connect your channels first.")

    try:
        await publisher.schedule(post, account.zernio_account_id,
                                 body.scheduled_for, body.timezone,
                                 platform=account.platform, zernio_key=zkey)
    except publisher.PublishError as e:
        await db.commit()
        raise HTTPException(e.status_code, e.message) from e

    await db.commit()
    await db.refresh(post)
    return post


@router.post("/sync", response_model=list[PostOut])
async def sync_posts(
    current: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> list[Post]:
    """Reconcile the user's scheduled posts with Zernio's real state (Zernio owns
    publish timing), then return the full, up-to-date list."""
    zkey = resolve_zernio_key(current)
    if zkey:
        scheduled = await db.scalars(
            select(Post).where(
                Post.user_id == current.id,
                Post.status == post_status.SCHEDULED,
                Post.zernio_post_id.is_not(None),
            )
        )
        changed = False
        for p in scheduled:
            before = p.status
            await publisher.sync_status(p, zkey)
            changed = changed or p.status != before
        if changed:
            await db.commit()
    rows = await db.scalars(
        select(Post).where(Post.user_id == current.id).order_by(Post.created_at.desc())
    )
    return list(rows)
